import type { Course, Instructor } from "@/types"

export const mockInstructors: Instructor[] = [
  {
    id: "1",
    name: "Jane Smith",
    title: "Senior Full Stack Developer",
    bio: "Jane has over 10 years of experience in web development and has worked with companies like Google and Facebook.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4.9,
    students: 15000,
    courses: 12,
    expertise: ["React", "Node.js", "TypeScript", "GraphQL"],
  },
  {
    id: "2",
    name: "Dr. Michael Johnson",
    title: "Data Science Professor",
    bio: "Dr. Johnson is a professor at MIT with expertise in machine learning and artificial intelligence.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4.8,
    students: 8500,
    courses: 8,
    expertise: ["Python", "Machine Learning", "Statistics", "TensorFlow"],
  },
  {
    id: "3",
    name: "Sarah Wilson",
    title: "UX/UI Design Lead",
    bio: "Sarah is a design lead at Apple with a passion for creating beautiful and intuitive user experiences.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4.9,
    students: 12000,
    courses: 15,
    expertise: ["Figma", "Adobe Creative Suite", "User Research", "Prototyping"],
  },
]

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    description: "Learn full-stack web development from scratch with HTML, CSS, JavaScript, React, Node.js, and more.",
    category: "Web Development",
    level: "Beginner",
    price: 99,
    duration: "40 hours",
    rating: 4.8,
    reviews: 1234,
    students: 15000,
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: mockInstructors[0],
  },
  {
    id: "2",
    title: "Data Science with Python",
    description: "Master data science and machine learning with Python, pandas, numpy, and scikit-learn.",
    category: "Data Science",
    level: "Intermediate",
    price: 149,
    duration: "60 hours",
    rating: 4.9,
    reviews: 856,
    students: 8500,
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: mockInstructors[1],
  },
  {
    id: "3",
    title: "UI/UX Design Fundamentals",
    description: "Learn the principles of user interface and user experience design with hands-on projects.",
    category: "Design",
    level: "Beginner",
    price: 79,
    duration: "25 hours",
    rating: 4.7,
    reviews: 642,
    students: 12000,
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: mockInstructors[2],
  },
  {
    id: "4",
    title: "Advanced React Development",
    description:
      "Take your React skills to the next level with advanced patterns, hooks, and performance optimization.",
    category: "Web Development",
    level: "Advanced",
    price: 199,
    duration: "35 hours",
    rating: 4.9,
    reviews: 423,
    students: 5200,
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: mockInstructors[0],
  },
  {
    id: "5",
    title: "Machine Learning Fundamentals",
    description: "Introduction to machine learning concepts, algorithms, and practical applications.",
    category: "Data Science",
    level: "Beginner",
    price: 129,
    duration: "45 hours",
    rating: 4.6,
    reviews: 789,
    students: 9800,
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: mockInstructors[1],
  },
  {
    id: "6",
    title: "Mobile App Design",
    description: "Design beautiful and functional mobile applications for iOS and Android platforms.",
    category: "Design",
    level: "Intermediate",
    price: 89,
    duration: "30 hours",
    rating: 4.8,
    reviews: 567,
    students: 7300,
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: mockInstructors[2],
  },
]
